// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/pages/login/components/banner.vue')['default']
    CanvasPanel: typeof import('./src/components/CanvasPanel.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Home: typeof import('./src/pages/home.vue')['default']
    Login: typeof import('./src/pages/login/index.vue')['default']
    LoginForm: typeof import('./src/pages/login/components/login-form.vue')['default']
    OptionPanel: typeof import('./src/components/OptionPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumbnail: typeof import('./src/components/Thumbnail.vue')['default']
    Workspace: typeof import('./src/pages/workspace.vue')['default']
  }
}
